Cinema/Models/Acteur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Models
{
    public class Acteur
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Image Profil")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilImageUrl { get; set; }
        [Display(Name = "Nom Complet")]
        [Required(ErrorMessage = "Full Name is required")]
        public string NomComplet { get; set; }
        [Display(Name = "Biographie")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }
        public List<Acteur_Film> Acteur_Films { get; set; }
    }
}

Cinema/Models/Acteur_Film.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Models
{
    public class Acteur_Film
    {
        public int? FilmId { get; set; }
        public Film Film { get; set; }
        public int? ActeurId { get; set; }
        public Acteur Acteur { get; set; }
    }
}

Cinema/Models/Cinemaa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Models
{
    public class Cinemaa
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Logo")]
        [Required(ErrorMessage = "Logo is required")]
        public string Logo { get; set; }
        [Display(Name = "Nom")]
        [Required(ErrorMessage = "Nom is required")]
        public string Nom { get; set; }
        [Display(Name = "Decription")]
        [Required(ErrorMessage = "Decription is required")]
        public string Description { get; set; }
        public List<Film> Films { get; set; }
    }
}

Cinema/Models/ErrorViewModel.cs
using System;

namespace Cinema.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cinema/Models/Film.cs
using Cinema.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Models
{
    public class Film
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Nom")]
        [Required(ErrorMessage = "Nom is required")]
        public string Nom { get; set; }
        [Display(Name = "Description")]
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }
        [Display(Name = "Prix")]
        [Required(ErrorMessage = "Prix is required")]
        public double Price { get; set; }
        [Display(Name = "Image")]
        [Required(ErrorMessage = "Image is required")]
        public string ImageUrl { get; set; }
        [Display(Name = "Date début")]
        [Required(ErrorMessage = "Date Début is required")]
        public DateTime DateDebut { get; set; }
        [Display(Name = "Date fin")]
        [Required(ErrorMessage = "Date fin is required")]
        public DateTime Datefin { get; set; }
        public CategorieFilm CategorieFilm { get; set; }
        public List<Acteur_Film> Acteur_Films { get; set; }
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinemaa Cinema { get; set; }
        public int ProducteurId { get; set; }
        [ForeignKey("ProducteurId")]
        public Producteur Producteur { get; set; }
    }
}

Cinema/Models/Producteur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Models
{
    public class Producteur
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Image Profil")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilImageUrl { get; set; }
        [Display(Name = "Nom Complet")]
        [Required(ErrorMessage = "Full Name is required")]
        public string NomComplet { get; set; }
        [Display(Name = "Biographie")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }
        public List<Film> Films { get; set; }
    }
}

Cinema/Controllers/ActeursController.cs
using Cinema.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    public class ActeursController : Controller
    {
        private readonly AppDbContext _context;
        public ActeursController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var data = _context.Actors.ToList();
            return View(data);
        }
    }
}

Cinema/Controllers/CinemasController.cs
using Cinema.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    public class CinemasController : Controller
    {
        private readonly AppDbContext _context;
        public CinemasController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _context.Cinemas.ToListAsync();
            return View(data);
        }
    }
}

Cinema/Controllers/FilmsController.cs
using Cinema.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    public class FilmsController : Controller
    {
        private readonly AppDbContext _context;
        public FilmsController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _context.Movies.Include(n=>n.Cinema).ToListAsync();
            return View(data);
        }
    }
}

Cinema/Controllers/HomeController.cs
using Cinema.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cinema/Controllers/ProducteursController.cs
using Cinema.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.Controllers
{
    public class ProducteursController : Controller
    {
        private readonly AppDbContext _context;
        public ProducteursController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _context.Producers.ToListAsync();
            return View(data);
        }
    }
}

Cinema/Views/Acteurs/Index.cshtml
@*Define model*@
@model IEnumerable<Acteur>
@*Define ViewData*@

@{
    ViewData["Title"] = "List of Actors";
}


@*Write a Code*@

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilImageUrl)</th>
                    <th>@Html.DisplayNameFor(model => model.NomComplet)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                   
                        <th>Actions</th>
                   
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilImageUrl" alt="@item.NomComplet" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.NomComplet)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                       
                            <td class="align-middle">
                                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                                <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                            </td>
                        

                    </tr>
                }
            </tbody>

        </table>
    </div></div>

Cinema/Views/Cinemas/Index.cshtml
@*Define model*@
@model IEnumerable<Cinemaa>
@*Define ViewData*@

@{
    ViewData["Title"] = "List of Producers";
}


@*Write a Code*@

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Logo)</th>
                    <th>@Html.DisplayNameFor(model => model.Nom)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>

                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.Nom" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Nom)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>

                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>


                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

Cinema/Views/Films/Index.cshtml
@model IEnumerable<Film>

@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Nom
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Nom">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Nom</p>
                            <p class="card-text"><b>Category: </b>@item.CategorieFilm</p>
                            <p class="card-text"><b>Start Date: </b>@item.DateDebut.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.Datefin.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.DateDebut && DateTime.Now <= item.Datefin)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.Datefin)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.Datefin) ? "disabled" : "")"
                                   asp-controller="Orders"
                                   asp-action="AddItemToShoppingCart"
                                   asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    </div>

Cinema/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cinema/Views/Producteurs/Index.cshtml
@*Define model*@
@model IEnumerable<Producteur>
@*Define ViewData*@

@{
    ViewData["Title"] = "List of Producers";
}


@*Write a Code*@

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilImageUrl)</th>
                    <th>@Html.DisplayNameFor(model => model.NomComplet)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>

                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilImageUrl" alt="@item.NomComplet" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.NomComplet)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>

                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>


                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

Cinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       <li class="navbar-nav flex-grow-1"></li>
                        <a class="nav-link text-dark" asp-controller="Films" asp-action="Index"></a>
                        <i class="badge-info bi-film">Films</i>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cinema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>